<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="10.0.11" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Runtime\PortableRuntimeIdentifierGraph.json"
                      LogicalName="Cxpm.Core.PortableRuntimeIdentifierGraph.json" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Cxpm.Tests" />
    <InternalsVisibleTo Include="Cxpm.Web" />
  </ItemGroup>

</Project>
